name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PUBLISH_ARTIFACTS: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: Build with JDK 11
        run: mvn -B install --no-transfer-progress -DskipTests

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Test with JDK 8
        run: mvn -v && mvn -B test

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Test with JDK 11          
        run: mvn -v && mvn -B test

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Test with JDK 17         
        run: mvn -v && mvn -B test
        
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Test with JDK 21
        run: mvn -v && mvn -B test
        
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
      - name: Test with JDK 24
        run: mvn -v && mvn -B test
      
      - name: Set up settings.xml for Sonatype
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Publish SNAPSHOT version to Sonatype (we can skip tests, since we only deploy, if the build workflow succeeded)
        run: mvn -v && mvn -B -P requireSnapshot --no-transfer-progress -DskipTests deploy --settings build/settings-sonatype.xml
        if: env.PUBLISH_ARTIFACTS == 'true'
        env:
          SONATYPE_USERNAME: yJQKaLoU
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PW_TOKEN }}
